### PR TITLE
Arabic translation by KUWAITNET

### PR DESCRIPTION
**Pull request by Bashar**
Arabic translation contribution for django-jet

### CODE REVIEW

**Comment by Bashar** [comment]
Just to note that I contributed to django, django-cms, django-rest-framework and other dozen django packages as maintainer or translator over transifex

**Comment by SalahAdDin** [comment]
:+1:

**Comment by f1nality** [comment]
Thanks for PR, merged!

**Comment by Bashar** [comment]
Most welcome :) 

I dropped an email about it just wondering if you got it?

**Comment by f1nality** [comment]
@Bashar Look like my email to ``@kuwaitnet.net`` (you and Sara) are not delivered. I've tried sending from ``@geex-art.som`` and ``@gmail.com`` but without success. But I receive your messages. Could you send me mail with any other hosting? gmail, etc. ?

**Comment by Bashar** [comment]
Hello @f1nality  Weird, should reach, we just have extra layer of protection there from spamexperts.com, try @kuwaitnet.com its on Gsuite

**Pull request merged**
