### PR TITLE
Localization

### PR DESCRIPTION
**Pull request by SalahAdDin**

### CODE REVIEW

**Comment by f1nality** [comment]
Thanks! 
But there are still some issues, have you generated localization files automatically? It produces not perfect files, that why I have manually edited localization to remove duplicates ("en", "ru" locales").

jet/locale/es/LC_MESSAGES/djangojs.po – is empty
jet/dashboard/locale/es/LC_MESSAGES/django.po dashboard/apps.py:8 Jet Dashboard – this label does not exit yet
jet/dashboard/locale/en/LC_MESSAGES/djangojs.po – no localization

Ideally "en" localization files need to be copied and updated with localization.

**Comment by SalahAdDin** [comment]
Well, yes, i have to remove `Jet Dashboard` label.

But, i don't understand why apply `./manage.py makemessages -l es -d djangojs` doesn't create these localization files.

So, i'll try with you contribute method.

**Comment by f1nality** [comment]
``makemessages`` searches for django.gettext which is wrapped in JET, so it won't find anything.
So you need just copy "en" locale folders in jet and jet.dashboard packages and rename them to "es" - that's all. After that translation can be made.

**Comment by SalahAdDin** [comment]
OK but, copy all files or only `djangojs.po` files?

**Comment by f1nality** [comment]
Oops, not just copy 😄 only *.po needed for translating, but it will be better if you push *.mo files too after finishing translation. Btw ``gulp`` command should also build *.mo files on update.

**Comment by SalahAdDin** [comment]
No man, i'm talking for translate, obviously i'll pr with both `.mo` and `.po` files hahahahahaha.

**Comment by f1nality** [comment]
Is translation finished?
Btw I have noticed different translation for "URL". 

> #: models.py:9 templates/admin/base.html:278
> msgid "URL"
> msgstr "URL"

But

> #: dashboard/modules.py:163
> msgid "URL"
> msgstr "LRU"

I thought URL is an international abbreviation and should be the same everywhere, at least in Spanish languages.

**Comment by f1nality** [comment]
@SalahAdDin whats with this translation? Does it have any problems or can be merged? I'm only a bit confused about LRU abbreviation.

**Comment by SalahAdDin** [comment]
URL in spanish correctly is LRU, but, URL it's good.
Can you change it?

**Comment by f1nality** [comment]
Yes, but what is the common practice for spanish websites? Do they use LRU or URL mostly?

**Comment by SalahAdDin** [comment]
Anglicism, i mean, URL.

**Pull request merged**
