### PR TITLE
Fix django 1.9 related-widget-wrapper error issue #52

### PR DESCRIPTION
**Pull request by iknite**
Hi, 

This is the merge between django 1.9.4 branch and the changes you make in django-jet so it fixes the issue #52. 

Cheers and Kudos!
E.

### CODE REVIEW

**Comment by jturmel** [comment]
@f1nality any plans to start merging in these various Django 1.9 and 1.10 PRs?

**Comment by SalahAdDin** [comment]
@jturmel I don't know but i want to know.

**Comment by f1nality** [comment]
This issue should be fixed in 0.1.5

**Comment by iknite** [comment]
Great!






On Sun, Jul 24, 2016 at 6:59 PM +0200, "Denis K." <notifications@github.com> wrote:












Closed #56.

**Pull request closed without merging**
