### PR TITLE
fix for issue #230

### PR DESCRIPTION
**Pull request by zodman**

### CODE REVIEW

**Comment by SalahAdDin** [comment]
:+1:

**Comment by all-4-1-1-4-all** [comment]
Please come to my Discord server so we can organize if you like:

* https://discord.gg/3yr5yeH

Welcome! 😄

**Comment by zodman** [comment]
now this PR fix issue #236  too!

**Comment by zodman** [comment]
this had a lot of features ...

**Comment by SalahAdDin** [comment]
@zodman, what's the problem?

**Comment by zodman** [comment]
1.- django.jQuery problem
2.- analytics token expiring

**Comment by SalahAdDin** [comment]
@f1nality man?

**Pull request closed without merging**
