### PR TITLE
Update master

### PR DESCRIPTION
**Pull request by f1nality**

### CODE REVIEW

**Comment by f1nality** [comment]
@SalahAdDin yes, you can check Live Demo. Its means that we took into account all experience with Django Jet and decided to create completely new version eliminating all problems of old version. For new Jet a whole team of our company will be dedicated so we can maintain and improve on regular basis. Django Jet will still be updated to fix critical problems and bugs, but new features won't be developed. We will make them in new version. 

what you think?

**Comment by edmenendez** [comment]
Is it backward compatible and under the same license?

**Comment by f1nality** [comment]
no, it uses different technologies. now it does not depend on django at all (can work with any backend, not even Python) and works as saas.

**Comment by edmenendez** [comment]
Is it possible you can help the community and give other people commit access to the current django-jet repo? There are lots of viable PRs that people would like to get merged into the project and it's much simpler than forking.

**Comment by f1nality** [comment]
@edmenendez while i'm still trying to look for critical problems and merge them I think it can be a good idea. Does anyone wants to maintain repository? It should be very responsible and skilled person, because one bad merge of Pull Request can lead to a lot of compatibility issues.

**Pull request merged**
