### PR TITLE
Add change message as tooltip to recent action dashboard module.

### PR DESCRIPTION
**Pull request by michaelkuty**
Add the information about action to the tooltip.

### CODE REVIEW

**Comment by f1nality** [comment]
@michaelkuty Hello!
entry.change_message has raw json data in it, it should be formatted somehow before showing to users as not only developers can be users of admin site.

**Comment by michaelkuty** [comment]
I have all messages in correct format, maybe if you write json message then is in json see my pictures
screen shot 2016-11-14 at 15 58 48
screen shot 2016-11-14 at 15 58 42

**Comment by f1nality** [comment]
@michaelkuty which django version do you use?

**Comment by michaelkuty** [comment]
(leonardo_csb) Michaels-MacBook:leonardo_csb michaelkuty$ pip freeze | grep D
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Django==1.8.14

**Comment by f1nality** [comment]
@michaelkuty yes, its an django related issue
Look, since 1.10 there is a special method get_change_message which would format change_message if it is a json string. 
1.10 https://github.com/django/django/blob/stable/1.10.x/django/contrib/admin/models.py
1.9 https://github.com/django/django/blob/stable/1.9.x/django/contrib/admin/models.py

So I think your PR whould be updated with some kind of ``get_change_message if get_change_message else change_message`` code

**Comment by michaelkuty** [comment]
@f1nality I added filter for achieving this

**Comment by f1nality** [comment]
@michaelkuty thanks for PR, merged

**Pull request merged**
