### PR TITLE
Update login page CSS

### PR DESCRIPTION
**Pull request by cdrx**
Currently on the login page, it is difficult to customise the login form because the elements on the page have a fixed position. For e.g., if you add a box underneath the login box, it overlays the login form:

screen shot 2016-01-06 at 23 38 21

With these changes the page should look the same but does support adding new elements to the login form:

screen shot 2016-01-06 at 23 41 13

### CODE REVIEW

**Comment by SalahAdDin** [comment]
:+1:

**Comment by f1nality** [comment]
0.9.0 login doesn't have fixed position, so now there shouldn't be problems with adding content to it.

**Comment by SalahAdDin** [comment]
This is interesting for me.

**Comment by f1nality** [comment]
What exactly do you want to know? Login page now can be customized exactly the same way as you customize default django admin login page because JET doesn't override login.html, so default django's is used.

**Pull request closed without merging**
