### PR TITLE
Date range filter

### PR DESCRIPTION
**Pull request by timur-orudzhov**
add support date range filter

screenshot

Code for date range filter was taken from - https://github.com/silentsokolov/django-admin-rangefilter

### CODE REVIEW

**Comment by SalahAdDin** [comment]
Why put you `django-form-admin` as requirement?

**Comment by timur-orudzhov** [comment]
@SalahAdDin, this app useful to render form as common admin form.

**Comment by timur-orudzhov** [comment]
@SalahAdDin Please, can you tell me, what i should change to include this pr to your package ?

**Comment by SalahAdDin** [comment]
This isn't my package.

@f1nality Help please.

**Comment by timur-orudzhov** [comment]
@f1nality can you consider this pr ?

**Comment by f1nality** [comment]
@timur-orudzhov thanks for this PR
So you've taken sources from django-admin-rangefilter and copied it to jet with some edits?
it would be nice to accomplish it without copying and overriding the whole sources, but just to add some js/html overrides which will fix possible compatibility problems.
Is it possible?

**Comment by timur-orudzhov** [comment]
@f1nality yes, it's possible.

**Comment by timur-orudzhov** [comment]
@f1nality done. could reconsider the pr ?

**Comment by f1nality** [comment]
@timur-orudzhov I have manually merged your PR to dev branch with some changes https://github.com/geex-arts/django-jet/commit/2e4120cebeebf327dca64194ecd33bc611865396
I've replaced webui popover dependency with custom jet's popover and made some refactoring.

So your PR is now available in dev branch and will be released in 1.0.3. Thanks!

**Comment by timur-orudzhov** [comment]
@f1nality thank you

**Pull request closed without merging**
