### PR TITLE
Support for Brazilian Portuguese localization

### PR DESCRIPTION
**Pull request by sedir**
I've translated from english sources and followed the contributing page instructions.

### CODE REVIEW

**Comment by f1nality** [comment]
@sedir hello and thanks for your translation!

Could you also translate jet's dashboard? Its translation files are in a separate folder https://github.com/geex-arts/django-jet/tree/master/jet/dashboard/locale

Btw has Brazilian Portuguese big differences compared to just Portuguese? Can we use this translation for just "pt" locale?

**Comment by sedir** [comment]
Sure I can translate. I just don't know if I have to make another pull request or reuse this one. I'm actually new on using this PR feature.

There are few differences between pt-pt and pt-br, but I guess there's no problem with the words used.

**Comment by SalahAdDin** [comment]
Until the repository owner or whoever have permissions over the repository doesn't merge the pull request, the user that did this pull request can made whatever change over the same without needed create other PR, ever you user the same branch from you are doing pull request.

**Comment by f1nality** [comment]
@sedir dashboard translation was made by @mord4z https://github.com/geex-arts/django-jet/pull/119 so full ``pt-br`` translation will be released in 1.0.2

**Pull request merged**
