### PR TITLE
Fix utf8 pronblems

### PR DESCRIPTION
**Pull request by Copperfield**
This commit should solve #136 issue

### CODE REVIEW

**Comment by SalahAdDin** [comment]
Does this work with python 3?

**Comment by Copperfield** [comment]
Actually I didn't try it, but it should work in Python 3.

**Comment by SalahAdDin** [comment]
I can test it :D

**Comment by SalahAdDin** [comment]
Well, please merge it @f1nality

**Comment by f1nality** [comment]
@Copperfield thanks for PR, but this one is more elegant https://github.com/geex-arts/django-jet/pull/138 anyway, fix should be released in 1.0.3

**Comment by Copperfield** [comment]
@f1nality I couldn't agree more.  Thanks you!

**Pull request closed without merging**
