### PR TITLE
Filebrowser support

### PR DESCRIPTION
**Pull request by polyn0m**
Added file browser support for https://github.com/smacker/django-filebrowser-no-grappelli

### CODE REVIEW

**Comment by SalahAdDin** [comment]
@polyn0m Try to create the properly `scss` file, as you can see, `django-jet` use now node for compile styles.

**Comment by polyn0m** [comment]
@SalahAdDin ok, on next week rewrite all styles

**Comment by SalahAdDin** [comment]
@polyn0m Looks here: https://github.com/geex-arts/django-jet/blob/dev/CONTRIBUTING.rst

**Comment by SalahAdDin** [comment]
@polyn0m Man?

**Comment by polyn0m** [comment]
@SalahAdDin now a have many work, i return to this task in next several weeks. Now close request and open new when did it.

**Comment by SalahAdDin** [comment]
Ok, thanks.

**Pull request closed without merging**
